services:
  sunflower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sunflower-dev
    ports:
      - 22222:22222
    depends_on:
      - postgres
      - mongodb
    environment:
      # https://github.com/Saebasol/sunflower/blob/main/sunflower/infrastructure/sanic/config.py
      SUNFLOWER_USE_ENV: "true"
      SUNFLOWER_PRODUCTION: "true"
      SUNFLOWER_HOST: "0.0.0.0"
      SUNFLOWER_PORT: "22222"
      SUNFLOWER_SENTRY_DSN: ""
      SUNFLOWER_GALLERYINFO_DB_URL: postgresql+asyncpg://heliotrope_user:heliotropepasswd@postgres-heliotrope-dev:5432/heliotrope_db
      SUNFLOWER_INFO_DB_URL: mongodb://heliotrope_user:heliotropepasswd@mongo-heliotrope-dev:27017
      SUNFLOWER_INDEX_FILES: '["index-korean.nozomi"]'

  postgres:
    image: postgres
    container_name: postgres-heliotrope-dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: heliotrope_user
      POSTGRES_PASSWORD: heliotropepasswd
      POSTGRES_DB: heliotrope_db

  mongodb:
    container_name: mongo-heliotrope-dev
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: heliotrope_user
      MONGO_INITDB_ROOT_PASSWORD: heliotropepasswd

volumes:
  mongodb_data:
  pgdata: